### ISSUE TITLE
func symbols showing twice (Linux/Lubuntu)

### ISSUE THREAD

**Issue by steviesama** [atom/symbols-view#188]
I'm using symbols-tree-view in Lubuntu and when I write functions, I they get listed in the view twice. Screenshot below.

![screen-shot](http://i.imgur.com/A5PRJYo.png)

**Comment by mijiturka** [comment]
Same with Atom 1.10.2 on Ubuntu 15.10. symbols-view 0.113.0 symbols-tree-view 0.13.2

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [symbols-tree-view](https://atom.io/packages/symbols-tree-view) package, not Atom itself. It may be that there is still a bug in symbols-view. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
