### ISSUE TITLE
No symbols found for html files

### ISSUE THREAD

**Issue by Albertc** [atom/symbols-view#209]
I can't see any symbol for .html language

Do I have to put something in .ctags file?

Thanks

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
