### ISSUE TITLE
Arrow Functions not recognized

### ISSUE THREAD

**Issue by Sltn29** [atom/symbols-view#221]
class methods declared via arrow functions are not recognized.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
