### ISSUE TITLE
Enhance by pulling info from atom-languageclient

### ISSUE THREAD

**Issue by ryanolsonx** [atom/symbols-view#247]
In considering how Atom can be used as a language server and to keep things moving forwards, I was thinking that it would be great if this package could support viewing symbols given from a language server. Is that something that you would welcome into this package? Or would I need to fork it and distribute as a separate package?

It could still fall back to tags but if your text file is in a language that you have a language server package for, it could use that.

**Comment by lee-dohm** [comment]
If I recall correctly, atom-ide-ui had some sort of separate symbols viewer that was completely independent of atom/symbols-view, so I would think that replicating that would be within the purview of the atom-ide-community packages? Or am I misunderstanding?

**Comment by ryanolsonx** [comment]
One idea someone came up with was to see if we would be able to simply make `symbols-view` read from either ctags OR LSP. So I was just curious on what maintainers of atom/symbols-view would think about that. 😄 

If the sole purpose and end-all functionality of `symbols-view` is to _only_ read from ctags. I understand.

But yeah, we can definitely create a separate package in `atom-ide-community` to handle that sort of thing.

**Comment by lee-dohm** [comment]
Thanks for bringing this up.

Upon reviewing with the team, we've decided that this isn't something that we want to maintain, especially since doing so would essentially mean we would have to keep up with whatever pace is established for atom-ide, which is something that we've already decided we don't have the bandwidth to do at this point. If that situation changes, we would be open to re-evaluating. For now, we're going to close this as something that we aren't going to work on and wouldn't be willing to accept a PR for.

Thanks for your passion and for understanding.
