### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by CanKer** [atom/symbols-view#257]
You have the core package "symbols-view" installed as a community package. See https://github.com/atom/atom/blob/master/packages/dalek/README.md for how this causes problems and instructions on how to correct the situation.
```
<unknown> (<embedded>:11:177493)
Generator.next (null:null:null)
step (<embedded>:11:177329)
process.processTicksAndRejections (internal/process/task_queues.js:86:5)
```

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
